# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aeb95fc57b92a8d9ddd7af141c3cafcd2cfe9e5ffab802c574994aad80213780b4520ab178d6d904ec57d755edbfef4fe70e31dc55206c41fb626f2c1bad142

test:
  secret_key_base: 8012611484c8205e8d135dbc3dcdd8b2fbbb38f1b41d02c2eccf3ae75d26cdd04e2ba90df34a5b650c9aeefad03b5f0264655134363e0364484d9f286231424d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
